package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/adaptocms/adapto-cms-cli/cmd"
	"github.com/spf13/cobra"
)

const (
	beginMarker = "<!-- commands:begin (generated by make docs) -->"
	endMarker   = "<!-- commands:end -->"
)

func main() {
	check := flag.Bool("check", false, "verify the README tree is current instead of writing it")
	flag.Parse()

	data, err := os.ReadFile("README.md")
	if err != nil {
		fatal(err)
	}

	before, rest, ok := strings.Cut(string(data), beginMarker)
	if !ok {
		fatal(fmt.Errorf("README.md: %q marker not found", beginMarker))
	}
	_, after, ok := strings.Cut(rest, endMarker)
	if !ok {
		fatal(fmt.Errorf("README.md: %q marker not found", endMarker))
	}

	out := before + beginMarker + "\n```\n" + renderTree(cmd.Root()) + "```\n" + endMarker + after
	if *check {
		if out != string(data) {
			fatal(fmt.Errorf("README.md command tree is stale: run make docs"))
		}
		fmt.Println("README.md command tree is current")
		return
	}
	if err := os.WriteFile("README.md", []byte(out), 0644); err != nil {
		fatal(err)
	}
	fmt.Println("README.md command tree regenerated")
}

func renderTree(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("adapto\n")
	walk(&b, root, "")
	return b.String()
}

func walk(b *strings.Builder, c *cobra.Command, prefix string) {
	kids := children(c)
	for i, k := range kids {
		connector, childPrefix := "├── ", prefix+"│   "
		if i == len(kids)-1 {
			connector, childPrefix = "└── ", prefix+"    "
		}
		line := prefix + connector + k.Use
		if pad := 44 - len(line); pad > 0 {
			line += strings.Repeat(" ", pad)
		} else {
			line += "  "
		}
		b.WriteString(line + k.Short + "\n")
		walk(b, k, childPrefix)
	}
}

func children(c *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, s := range c.Commands() {
		if s.Hidden || s.Name() == "help" || s.Name() == "completion" {
			continue
		}
		out = append(out, s)
	}
	return out
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
